version: "3.3"
services:
    converter:
      container_name: converter
      build: .
      env_file: .env
      ports:
        - "8080:8080"
      volumes:
        - .:/app
        - /app/venv/
      links:
        - mongo
      networks:
        - local
    mongo:
      image: mongo:latest
      container_name: mongo
      volumes:
        - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      ports:
        - 27017:27017
      networks:
        - local
    redis:
      image: redis
      container_name: redis
      ports:
        - 6379:6379
      networks:
        - local
    celery:
      container_name: celery
      build:
        context: .
      command: celery -A server worker -l INFO
      env_file: .env
      depends_on:
        - mongo
        - redis
      volumes:
        - .:/app
      networks:
        - local

networks:
  local:
    driver: bridge
    name: local
