apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns
  labels:
    app: ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: ns
    spec:
      containers:
        - name: ns
          image: nilay103/k8snotifications
          envFrom:
            - configMapRef:
                name: ns-configmap
            - secretRef:
                name: ns-secret
