version: "3.3"
services:
  auth:
    container_name: auth
    build:
      context: .
    links:
      - db
    ports:
      - "5000:5000"
    image: nilay103/k8sauth
    networks:
      - external_network
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - external_network

networks:
  external_network:
    name: local
    external: true
